CTP_VERSION := 6.7.13

# 把点号替换成空格，变成列表：6 6 1
CTP_VER_PARTS := $(subst ., ,$(CTP_VERSION))
VER_MAJOR := $(word 1,$(CTP_VER_PARTS))
VER_MINOR := $(word 2,$(CTP_VER_PARTS))
VER_PATCH := $(word 3,$(CTP_VER_PARTS))
# 计算数值：major*1000000 + minor*1000 + patch

CTP_VER := $(shell echo $$(( $(VER_MAJOR)*1000000 + $(VER_MINOR)*1000 + $(VER_PATCH) )))
CTP_INC := ./depend/ctp/v$(CTP_VERSION)/include/

PRO_SRC=$(foreach dir,src/broker/trade/,$(wildcard $(dir)/*.cpp))
PRO_DEPS := $(PRO_SRC:%.cpp=%.d)
PRO_OBJS := $(PRO_DEPS:%.d=%.o)

PRO_OUT_PATH=./dist/obj/server

OBJS_NODIR := $(notdir $(PRO_OBJS))

P_WIN64_OBJS := $(addprefix $(PRO_OUT_PATH)/win64/,$(OBJS_NODIR)) 

PRO_OBJ_win64=./dist/server/win64/ctp_sandbox.exe

TARGET_OBJ_WIN64 := dist/obj/server/win64/
TARGET_WIN64 := dist/server/win64/

all: win64 

win64: $(TARGET_OBJ_WIN64) $(TARGET_WIN64) $(PRO_OBJ_win64)

$(PRO_OBJ_win64) : $(P_WIN64_OBJS) 
	x86_64-w64-mingw32-g++ -I$(CTP_INC) -DCTP_VER=$(CTP_VER) -L./depend/event/lib/win64 -Wl,-rpath,./ -g -o $@ $(P_WIN64_OBJS) -levent-2-1-7 -levent_core-2-1-7 -levent_extra-2-1-7 -lsqlite3 -lws2_32

dist/obj/server/win64/%.o: src/broker/trade/%.cpp
	x86_64-w64-mingw32-gcc -I$(CTP_INC) -DCTP_VER=$(CTP_VER) -I./depend/event/include  -I./src/public -g -c $< -o $@

$(TARGET_OBJ_WIN64):
	@-mkdir -p $@

$(TARGET_WIN64):
	@-mkdir -p $@

clean:
	rm -rf $(P_WIN64_OBJS) $(PRO_OBJ_win64)

# 声明伪目标，不会和文件重名冲突
.PHONY: clean

