CTP_6.7=./depend/ctp/v6.7.11/include/
CTP_6.6=./depend/ctp/ThostApi6.6.1P/include/

CTP_VERSION=CTP_6_7

CTP_INC=$(CTP_6.7)

PRO_SRC=$(foreach dir,src/api/trade/,$(wildcard $(dir)/*.cpp))
PRO_SRC_net=$(foreach dir,src/api/net/,$(wildcard $(dir)/*.cpp))

PRO_OBJS := $(PRO_SRC:%.cpp=%.o)
PRO_OBJS_net := $(PRO_SRC_net:%.cpp=%.o)

PRO_OUT_PATH=./dist/obj/api

OBJS_NODIR_a := $(notdir $(PRO_OBJS))
OBJS_NODIR_b := $(notdir $(PRO_OBJS_net))

P_DEBUG_OBJS_a := $(addprefix $(PRO_OUT_PATH)/debug/,$(OBJS_NODIR_a)) 
P_DEBUG_OBJS_b := $(addprefix $(PRO_OUT_PATH)/debug/net/,$(OBJS_NODIR_b)) 

P_DEBUG_OBJS := $(P_DEBUG_OBJS_a) $(P_DEBUG_OBJS_b)

P_RELEASE_OBJS_a := $(addprefix $(PRO_OUT_PATH)/release/,$(OBJS_NODIR_a)) 
P_RELEASE_OBJS_b := $(addprefix $(PRO_OUT_PATH)/release/net/,$(OBJS_NODIR_b)) 

P_DEBUG_OBJS := $(P_RELEASE_OBJS_a) $(P_RELEASE_OBJS_b)

PRO_OBJ_debug=./dist/api/debug/thosttraderapi_se.so
PRO_OBJ_release=./dist/api/release/thosttraderapi_se.so

TARGET_OBJ_DEBUG := dist/obj/api/debug/net/
TARGET_OBJ_RELEASE := dist/obj/api/release/net/
TARGET_DEBUG := dist/api/debug/
TARGET_RELEASE := dist/api/release/

all: debug release

debug: $(TARGET_OBJ_DEBUG) $(TARGET_DEBUG) $(PRO_OBJ_debug)

release: $(TARGET_OBJ_RELEASE) $(TARGET_RELEASE) $(PRO_OBJ_release)

$(PRO_OBJ_debug) : $(P_DEBUG_OBJS_a) $(P_DEBUG_OBJS_b)
	g++ -fPIC -Wl,-rpath,./ -shared -rdynamic  -Wl,--unresolved-symbols=ignore-in-shared-libs -Wl,-soname,thosttraderapi_se.so -g -o $@ $(P_DEBUG_OBJS_a) $(P_DEBUG_OBJS_b) -levent -levent_pthreads

dist/obj/api/debug/%.o: src/api/trade/%.cpp
	gcc -I$(CTP_INC) -D$(CTP_VERSION) -I./src/public -I./src/api/net  -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -g -c $< -o $@

dist/obj/api/debug/net/%.o: src/api/net/%.cpp
	gcc -I$(CTP_INC) -D$(CTP_VERSION) -I./src/public -I./src/api/net  -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -g -c $< -o $@

$(PRO_OBJ_release) : $(P_RELEASE_OBJS_a) $(P_RELEASE_OBJS_b)
	g++ -Wl,-rpath,./ -shared -rdynamic  -Wl,--unresolved-symbols=ignore-in-shared-libs -Wl,-soname,thosttraderapi_se.so -O3 -o $@ $(P_DEBUG_OBJS_a) $(P_DEBUG_OBJS_b) -levent -levent_pthreads 

dist/obj/api/release/%.o: src/api/trade/%.cpp
	gcc -I$(CTP_INC) -D$(CTP_VERSION) -I./src/public -I./src/api/net  -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -g -c $< -o $@

dist/obj/api/release/net/%.o: src/api/net/%.cpp
	gcc -I$(CTP_INC) -D$(CTP_VERSION) -I./src/public -I./src/api/net  -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -g -c $< -o $@


$(TARGET_OBJ_DEBUG):
	@-mkdir -p $@

$(TARGET_DEBUG):
	@-mkdir -p $@

$(TARGET_OBJ_RELEASE):
	@-mkdir -p $@

$(TARGET_RELEASE):
	@-mkdir -p $@

clean:
	rm -rf $(P_DEBUG_OBJS) $(PRO_OBJ_debug)
	rm -rf $(P_RELEASE_OBJS) $(PRO_OBJ_release)

# 声明伪目标，不会和文件重名冲突
.PHONY: clean

