CTP_VERSION := 6.7.13

# 把点号替换成空格，变成列表：6 6 1
CTP_VER_PARTS := $(subst ., ,$(CTP_VERSION))
VER_MAJOR := $(word 1,$(CTP_VER_PARTS))
VER_MINOR := $(word 2,$(CTP_VER_PARTS))
VER_PATCH := $(word 3,$(CTP_VER_PARTS))
# 计算数值：major*1000000 + minor*1000 + patch

CTP_VER := $(shell echo $$(( $(VER_MAJOR)*1000000 + $(VER_MINOR)*1000 + $(VER_PATCH) )))
CTP_INC := ./depend/ctp/v$(CTP_VERSION)/include/

PRO_SRC=$(foreach dir,src/broker/trade/,$(wildcard $(dir)/*.cpp))
PRO_DEPS := $(PRO_SRC:%.cpp=%.d)
PRO_OBJS := $(PRO_DEPS:%.d=%.o)

PRO_OUT_PATH=./dist/obj/server

OBJS_NODIR := $(notdir $(PRO_OBJS))

P_DEBUG_OBJS := $(addprefix $(PRO_OUT_PATH)/debug/,$(OBJS_NODIR)) 

P_RELEASE_OBJS := $(addprefix $(PRO_OUT_PATH)/release/,$(OBJS_NODIR)) 

PRO_OBJ_debug=./dist/server/debug/ctp_sandbox.exe
PRO_OBJ_release=./dist/server/release/ctp_sandbox.exe


TARGET_OBJ_DEBUG := dist/obj/server/debug/
TARGET_OBJ_RELEASE := dist/obj/server/release/
TARGET_DEBUG := dist/server/debug/
TARGET_RELEASE := dist/server/release/

all: debug release

debug: $(TARGET_OBJ_DEBUG) $(TARGET_DEBUG) $(PRO_OBJ_debug)

release: $(TARGET_OBJ_RELEASE) $(TARGET_RELEASE) $(PRO_OBJ_release)

$(PRO_OBJ_debug) : $(P_DEBUG_OBJS) 
	g++ -I$(CTP_6.7) -Wl,-rpath,./ -g -fsanitize=address -o $@ $(P_DEBUG_OBJS) -levent -levent_pthreads -lsqlite3

dist/obj/server/debug/%.o: src/broker/trade/%.cpp
	gcc -I$(CTP_INC) -DCTP_VER=$(CTP_VER) -I./src/public -g -fsanitize=address -c $< -o $@

$(PRO_OBJ_release) : $(P_RELEASE_OBJS) 
	g++ -I$(CTP_6.7) -Wl,-rpath,./ -O3 -o $@ $(P_RELEASE_OBJS) -levent -levent_pthreads -lsqlite3

dist/obj/server/release/%.o: src/broker/trade/%.cpp
	gcc -I$(CTP_INC) -DCTP_VER=$(CTP_VER) -I./src/public -O3 -c $< -o $@

$(TARGET_OBJ_DEBUG):
	@-mkdir -p $@

$(TARGET_DEBUG):
	@-mkdir -p $@

$(TARGET_OBJ_RELEASE):
	@-mkdir -p $@

$(TARGET_RELEASE):
	@-mkdir -p $@

clean:
	rm -rf $(P_DEBUG_OBJS) $(PRO_OBJ_debug)
	rm -rf $(P_RELEASE_OBJS) $(PRO_OBJ_release)

# 声明伪目标，不会和文件重名冲突
.PHONY: clean

