#pragma once

typedef enum TradeSpi_FuncID
{
	Spi_OnFrontConnected = 0,
	Spi_OnFrontDisconnected,
	Spi_OnHeartBeatWarning,
	Spi_OnRspAuthenticate,
	Spi_OnRspUserLogin,
	Spi_OnRspUserLogout,
	Spi_OnRspUserPasswordUpdate,
	Spi_OnRspTradingAccountPasswordUpdate,
	Spi_OnRspUserAuthMethod,
	Spi_OnRspGenUserCaptcha,
	Spi_OnRspGenUserText,
	Spi_OnRspOrderInsert,
	Spi_OnRspParkedOrderInsert,
	Spi_OnRspParkedOrderAction,
	Spi_OnRspOrderAction,
	Spi_OnRspQryMaxOrderVolume,
	Spi_OnRspSettlementInfoConfirm,
	Spi_OnRspRemoveParkedOrder,
	Spi_OnRspRemoveParkedOrderAction,
	Spi_OnRspExecOrderInsert,
	Spi_OnRspExecOrderAction,
	Spi_OnRspForQuoteInsert,
	Spi_OnRspQuoteInsert,
	Spi_OnRspQuoteAction,
	Spi_OnRspBatchOrderAction,
	Spi_OnRspOptionSelfCloseInsert,
	Spi_OnRspOptionSelfCloseAction,
	Spi_OnRspCombActionInsert,
	Spi_OnRspQryOrder,
	Spi_OnRspQryTrade,
	Spi_OnRspQryInvestorPosition,
	Spi_OnRspQryTradingAccount,
	Spi_OnRspQryInvestor,
	Spi_OnRspQryTradingCode,
	Spi_OnRspQryInstrumentMarginRate,
	Spi_OnRspQryInstrumentCommissionRate,
	Spi_OnRspQryUserSession,
	Spi_OnRspQryExchange,
	Spi_OnRspQryProduct,
	Spi_OnRspQryInstrument,
	Spi_OnRspQryDepthMarketData,
	Spi_OnRspQryTraderOffer,
	Spi_OnRspQrySettlementInfo,
	Spi_OnRspQryTransferBank,
	Spi_OnRspQryInvestorPositionDetail,
	Spi_OnRspQryNotice,
	Spi_OnRspQrySettlementInfoConfirm,
	Spi_OnRspQryInvestorPositionCombineDetail,
	Spi_OnRspQryCFMMCTradingAccountKey,
	Spi_OnRspQryEWarrantOffset,
	Spi_OnRspQryInvestorProductGroupMargin,
	Spi_OnRspQryExchangeMarginRate,
	Spi_OnRspQryExchangeMarginRateAdjust,
	Spi_OnRspQryExchangeRate,
	Spi_OnRspQrySecAgentACIDMap,
	Spi_OnRspQryProductExchRate,
	Spi_OnRspQryProductGroup,
	Spi_OnRspQryMMInstrumentCommissionRate,
	Spi_OnRspQryMMOptionInstrCommRate,
	Spi_OnRspQryInstrumentOrderCommRate,
	Spi_OnRspQrySecAgentTradingAccount,
	Spi_OnRspQrySecAgentCheckMode,
	Spi_OnRspQrySecAgentTradeInfo,
	Spi_OnRspQryOptionInstrTradeCost,
	Spi_OnRspQryOptionInstrCommRate,
	Spi_OnRspQryExecOrder,
	Spi_OnRspQryForQuote,
	Spi_OnRspQryQuote,
	Spi_OnRspQryOptionSelfClose,
	Spi_OnRspQryInvestUnit,
	Spi_OnRspQryCombInstrumentGuard,
	Spi_OnRspQryCombAction,
	Spi_OnRspQryTransferSerial,
	Spi_OnRspQryAccountregister,
	Spi_OnRspError,
	Spi_OnRtnOrder,
	Spi_OnRtnTrade,
	Spi_OnErrRtnOrderInsert,
	Spi_OnErrRtnOrderAction,
	Spi_OnRtnInstrumentStatus,
	Spi_OnRtnBulletin,
	Spi_OnRtnTradingNotice,
	Spi_OnRtnErrorConditionalOrder,
	Spi_OnRtnExecOrder,
	Spi_OnErrRtnExecOrderInsert,
	Spi_OnErrRtnExecOrderAction,
	Spi_OnErrRtnForQuoteInsert,
	Spi_OnRtnQuote,
	Spi_OnErrRtnQuoteInsert,
	Spi_OnErrRtnQuoteAction,
	Spi_OnRtnForQuoteRsp,
	Spi_OnRtnCFMMCTradingAccountToken,
	Spi_OnErrRtnBatchOrderAction,
	Spi_OnRtnOptionSelfClose,
	Spi_OnErrRtnOptionSelfCloseInsert,
	Spi_OnErrRtnOptionSelfCloseAction,
	Spi_OnRtnCombAction,
	Spi_OnErrRtnCombActionInsert,
	Spi_OnRspQryContractBank,
	Spi_OnRspQryParkedOrder,
	Spi_OnRspQryParkedOrderAction,
	Spi_OnRspQryTradingNotice,
	Spi_OnRspQryBrokerTradingParams,
	Spi_OnRspQryBrokerTradingAlgos,
	Spi_OnRspQueryCFMMCTradingAccountToken,
	Spi_OnRtnFromBankToFutureByBank,
	Spi_OnRtnFromFutureToBankByBank,
	Spi_OnRtnRepealFromBankToFutureByBank,
	Spi_OnRtnRepealFromFutureToBankByBank,
	Spi_OnRtnFromBankToFutureByFuture,
	Spi_OnRtnFromFutureToBankByFuture,
	Spi_OnRtnRepealFromBankToFutureByFutureManual,
	Spi_OnRtnRepealFromFutureToBankByFutureManual,
	Spi_OnRtnQueryBankBalanceByFuture,
	Spi_OnErrRtnBankToFutureByFuture,
	Spi_OnErrRtnFutureToBankByFuture,
	Spi_OnErrRtnRepealBankToFutureByFutureManual,
	Spi_OnErrRtnRepealFutureToBankByFutureManual,
	Spi_OnErrRtnQueryBankBalanceByFuture,
	Spi_OnRtnRepealFromBankToFutureByFuture,
	Spi_OnRtnRepealFromFutureToBankByFuture,
	Spi_OnRspFromBankToFutureByFuture,
	Spi_OnRspFromFutureToBankByFuture,
	Spi_OnRspQueryBankAccountMoneyByFuture,
	Spi_OnRtnOpenAccountByBank,
	Spi_OnRtnCancelAccountByBank,
	Spi_OnRtnChangeAccountByBank,
	Spi_OnRspQryClassifiedInstrument,
	Spi_OnRspQryCombPromotionParam,
	Spi_OnRspQryRiskSettleInvstPosition,
	Spi_OnRspQryRiskSettleProductStatus,
	Spi_OnRspQrySPBMFutureParameter,
	Spi_OnRspQrySPBMOptionParameter,
	Spi_OnRspQrySPBMIntraParameter,
	Spi_OnRspQrySPBMInterParameter,
	Spi_OnRspQrySPBMPortfDefinition,
	Spi_OnRspQrySPBMInvestorPortfDef,
	Spi_OnRspQryInvestorPortfMarginRatio,
	Spi_OnRspQryInvestorProdSPBMDetail,
	Spi_OnRspQryInvestorCommoditySPMMMargin,
	Spi_OnRspQryInvestorCommodityGroupSPMMMargin,
	Spi_OnRspQrySPMMInstParam,
	Spi_OnRspQrySPMMProductParam,
	Spi_OnRspQrySPBMAddOnInterParameter,
	Spi_OnRspQryRCAMSCombProductInfo,
	Spi_OnRspQryRCAMSInstrParameter,
	Spi_OnRspQryRCAMSIntraParameter,
	Spi_OnRspQryRCAMSInterParameter,
	Spi_OnRspQryRCAMSShortOptAdjustParam,
	Spi_OnRspQryRCAMSInvestorCombPosition,
	Spi_OnRspQryInvestorProdRCAMSMargin,
	Spi_OnRspQryRULEInstrParameter,
	Spi_OnRspQryRULEIntraParameter,
	Spi_OnRspQryRULEInterParameter,
	Spi_OnRspQryInvestorProdRULEMargin,
	Spi_OnRspQryInvestorPortfSetting,
	Spi_OnRspQryInvestorInfoCommRec,
	Spi_OnRspQryCombLeg,
	Spi_OnRspOffsetSetting,
	Spi_OnRspCancelOffsetSetting,
	Spi_OnRtnOffsetSetting,
	Spi_OnErrRtnOffsetSetting,
	Spi_OnErrRtnCancelOffsetSetting,
	Spi_OnRspQryOffsetSetting,
	Spi_CallbackCount
}TradeSpi_FuncID;

class CThostFtdcTraderSpi;

typedef void (CThostFtdcTraderSpi::*TradeSpi_Func_0)(void);
typedef void (CThostFtdcTraderSpi::*TradeSpi_Func_1)(void * p1);
typedef void (CThostFtdcTraderSpi::*TradeSpi_Func_2)(void * p1,void * p2);
typedef void (CThostFtdcTraderSpi::*TradeSpi_Func_3)(void * p1,void * p2,int nRequestID);
typedef void (CThostFtdcTraderSpi::*TradeSpi_Func_4)(void * p1,void * p2,int nRequestID,bool bIsLast);

typedef union FuncionPtr
{
	TradeSpi_Func_0 func_0;
	TradeSpi_Func_1 func_1;
	TradeSpi_Func_2 func_2;
	TradeSpi_Func_3 func_3;
	TradeSpi_Func_4 func_4;
}FuncionPtr;

typedef struct TradeSpi_CallbackInfo
{
	int psize[4];
	int p_cnt;
	int nouse;
	FuncionPtr func;
	const char * name;
}TradeSpi_CallbackInfo;

extern TradeSpi_CallbackInfo * g_spi_callback_list;